Лабораторная работа 1.3

Импортитуем необходимые библиотеки

In [51]:
import numpy as np 
import matplotlib.pyplot as plt
import random

Задаём число обусловленности, размерность матрицы и решение СЛАУ

In [52]:
cond=float(input('Задайте число обусловленности: '))
n=int(input('Задайте размерность матрицы: '))
result_X=np.random.sample(n).reshape(-1, 1)
result_X

array([[0.46773642],
       [0.04614188],
       [0.90679354],
       [0.21101779],
       [0.47229824],
       [0.95240211],
       [0.13616326],
       [0.31090132],
       [0.35019147],
       [0.98887119]])

Задаём элементы на главной диагонали, создаём треугольную матрицу

In [53]:
lambda1=1
lambda2=cond
lambda_n=random.uniform(1,cond)
u=np.full(n-2,lambda_n)
v=np.concatenate((np.array([lambda1,cond]),u))
D=np.diag(v)
T=np.tri(n)
G=np.diag(np.ones(n))
B=T+D-G

Cоздаём ортогональную матрицу

In [54]:
E=np.eye(n)
w=np.random.sample(n)
Q=E-2*w*w.reshape(-1, 1)/np.linalg.norm(w)**2

Создаём матрицу и вычисяем правую часть СЛАУ по известной матрице

In [55]:
A=np.dot(np.linalg.inv(Q),B)
A=np.dot(A, Q)
b=np.dot(A,result_X)
A,b

(array([[ 1.02600735e+00, -1.11443798e+00,  1.60237506e+00,
          1.27820038e+00,  6.88804140e-01,  2.35617785e-01,
          6.81155211e-01,  1.21515180e+00,  1.24606476e+00,
          1.74433725e+00],
        [-1.01814610e+00,  8.68185268e+01, -1.36300335e+01,
         -1.09111444e+01, -6.51637361e+00, -3.21928151e+00,
         -6.10417949e+00, -9.45846389e+00, -9.28140891e+00,
         -1.22490582e+01],
        [ 7.98394103e-02, -1.43233094e+01,  2.79885585e+01,
          3.27452654e+00,  1.41490060e+00, -6.00389454e-02,
          1.58589015e+00,  3.61541468e+00,  3.93685695e+00,
          5.91973825e+00],
        [ 2.09005234e-01, -1.14774081e+01,  3.77963477e+00,
          2.60563119e+01,  8.89021355e-01, -1.56653222e-01,
          1.03727313e+00,  2.51635728e+00,  2.77471651e+00,
          4.23033879e+00],
        [ 4.70336694e-01, -6.51049232e+00,  1.92304017e+00,
          1.72460516e+00,  2.40545304e+01, -2.32563141e-01,
          2.98362531e-01,  9.66039694e-01,  1.117211

Зададим возмущение матрицы коэффициентов

In [56]:
F=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        k=2*(0.5-random.random())*A[i][j]*0.02
        A[i][j]+=k
        F[i][j]+=k       
A,F

(array([[ 1.03438660e+00, -1.11721067e+00,  1.60233080e+00,
          1.29314756e+00,  7.00090290e-01,  2.37350802e-01,
          6.74359605e-01,  1.23649460e+00,  1.23718983e+00,
          1.77541960e+00],
        [-1.01366637e+00,  8.54801701e+01, -1.35517164e+01,
         -1.08838132e+01, -6.48587131e+00, -3.21174690e+00,
         -6.07627556e+00, -9.59252121e+00, -9.18392709e+00,
         -1.23864861e+01],
        [ 8.01437488e-02, -1.41227305e+01,  2.77670644e+01,
          3.25605151e+00,  1.41518175e+00, -5.99254366e-02,
          1.56495092e+00,  3.62317886e+00,  3.96530039e+00,
          5.87161204e+00],
        [ 2.08800681e-01, -1.13667566e+01,  3.84708043e+00,
          2.60941979e+01,  8.74977474e-01, -1.54221480e-01,
          1.02247624e+00,  2.52252375e+00,  2.79114019e+00,
          4.28714836e+00],
        [ 4.75354937e-01, -6.53672493e+00,  1.90902853e+00,
          1.74720992e+00,  2.38906035e+01, -2.30858270e-01,
          2.95384413e-01,  9.72339245e-01,  1.117088

Сделаем QR разложение матрицы А

In [57]:
Z=np.zeros((n,n))
def QR_decomposition(C,B):
    R=np.zeros((n,n))
    B[0:,0]=C[0:,0]
    B[0:,0]=B[0:,0]/np.linalg.norm(B[0:,0])
    for i in range(1,n):
        B[0:,i]=C[0:,i]
        for j in range(i):
            B[0:,i]-=np.dot(np.dot(C[0:,i],B[0:,j])/np.dot(B[0:,j],B[0:,j]),B[0:,j])
        B[0:,i]=B[0:,i]/np.linalg.norm(B[0:,i])
    for i in range(n):
        for j in range(i,n):
            R[i,j]+=np.dot(B[0:,i],C[0:,j])
    composite_matrix=np.hstack([R,E])
    j=n-1
    while j>=0:
        composite_matrix[j,j:]=composite_matrix[j,j:]/composite_matrix[j,j]
        i=j-1
        while i>=0:
            composite_matrix[i,j:]=composite_matrix[i,j:]-composite_matrix[j,j:]*composite_matrix[i,j]
            i-=1
        j-=1
    inv_R=composite_matrix[0:,n:]
    return [inv_R,B]

In [58]:
X=np.dot(QR_decomposition(A,Z)[0],np.transpose(QR_decomposition(A,Z)[1]))
X=np.dot(X,b)
X

array([[0.41370044],
       [0.04739697],
       [0.91597741],
       [0.20497404],
       [0.47529647],
       [0.94104688],
       [0.13399488],
       [0.31008472],
       [0.34467555],
       [0.99622918]])

Вычислим норму ошибки

In [59]:
np.linalg.norm(result_X-X,2)/np.linalg.norm(result_X,2)

np.float64(0.030861401009569134)

Вычислим норму невязки

In [60]:
np.linalg.norm(np.dot(A,X)-b)

np.float64(1.742731902818358e-14)

In [61]:
np.linalg.norm(F)/np.linalg.norm(A)

np.float64(0.013127785540651268)

Вычисим число обусловленности матрицы

In [62]:
cond_A=np.linalg.norm(A,2)*np.linalg.norm(np.linalg.inv(A),2)
cond_A

np.float64(98.6387934845234)

Проверим выполнение неравенства

In [63]:
np.linalg.norm(result_X-X,2)/np.linalg.norm(X,2)<=cond_A/(1-cond_A*np.linalg.norm(F)/np.linalg.norm(A))*np.linalg.norm(F)/np.linalg.norm(A)

np.False_