ЛАБОРАТОРНАЯ РАБОТА 1.6

In [2]:
import numpy as np 
import matplotlib.pyplot as plt 

In [3]:
eps = 0.01
n = 3
many_lam = []

In [4]:
for i in range(1, n + 1):
    many_lam.append(np.random.randint(10 * (i - 1), 10 * i))
many_lam += np.random.sample(n)
many_lam

array([ 2.16373044, 17.67780134, 21.56228224])

In [5]:
def create_matrix_with_eignvalues(eignvalues, n):
    random_matrix = np.random.rand(n, n)
    Q, _ = np.linalg.qr(random_matrix)
    D = np.diag(eignvalues)
    A = Q.T @ D @ Q
    return A
A = create_matrix_with_eignvalues(many_lam, n)
A

array([[19.77417908, -1.41652903, -1.34139113],
       [-1.41652903, 13.38092273,  8.25827256],
       [-1.34139113,  8.25827256,  8.24871221]])

In [6]:
H = A

In [8]:
def jacobi_method(A, eps, n):    
    eigenvectors = np.eye(n)
    T = np.copy(A)
    K = np.triu(T, 1)
    K = np.abs(K)
    it = 0
    while K.max() ** 2 > eps:
        it += 1
        G = np.eye(n)
        F = np.triu(T,1)
        p, q = np.unravel_index(np.argmax(np.abs(F)), F.shape)
        
        C = np.sqrt(1 / (1 + (2 * T[p, q] / (T[p, p] - T[q, q])) ** 2))
        s = np.sqrt((1 - C) / 2)
        c = np.sqrt((1 + C) / 2)

        for i in range(n):
            t = T[i, p]
            g = eigenvectors[i, p]
            T[i, p] = c * t + s * T[i, q]
            T[i, q] = s * t - c * T[i, q]
    
        for j in range(n):
            t = T[p, j]
            g = eigenvectors[p, j]
            T[p, j] = c * t + s * T[q, j]
            T[q, j] = s * t - c * T[q, j]
        
        G[p, p] = c
        G[p, q] = s
        G[q, p] = -s
        G[q, q] = c
     
        eigenvectors =  np.dot(eigenvectors, G)
        K = np.triu(T, 1)
        K = np.abs(K)
    eigenvalues = np.diag(T)
    return [T, eigenvectors, it]
jacobi_method(A, eps, n)

[array([[1.76778019e+01, 1.48150529e-03, 1.88044025e-15],
        [1.48150529e-03, 2.15622817e+01, 1.55514936e-05],
        [2.66453526e-15, 1.55514936e-05, 2.16373044e+00]]),
 array([[ 0.55139749,  0.83386917,  0.02496022],
        [-0.68993384,  0.43899153,  0.57556732],
        [ 0.46899052, -0.33458727,  0.81737338]]),
 7]